### ISSUE TITLE
APIML port 8544 in double

### ISSUE THREAD

**Issue by F-LEMANER** [zowe/community#504]
Hello,
The ZOWE STC fails to initialize because it cannot open port 8544 which is the one affected to ZOWE_ZLUX_SERVER_HTTPS

2020-04-16 11:47:41.820 <ZWED:16777784> IBTZWE0 WARN (_zsf.network,webserver.js:106) ZWED0071W - Unexpected error on server 0.0.0.0
Error: bind EACCES 0.0.0.0:8544                                                                                                    
    at listenOnMasterHandle (net.js:1382:18)                                                                                       
    at rr (internal/cluster/child.js:132:12)                                                                                       
    at Worker.<anonymous> (internal/cluster/child.js:99:7)                                                                         
    at process.onInternalMessage (internal/cluster/utils.js:47:8)                                                                  
    at process.emit (events.js:323:22)                                                                                             
    at emit (internal/child_process.js:897:12)                                                                                     
    at processTicksAndRejections (internal/process/task_queues.js:85:21)  

"CATALOG_PORT": "7552",           
"JOBS_API_PORT": "8545",          
"ZOWE_IP_ADDRESS": "126.5.173.11",
"LOGNAME": "IBTZWE0",             
"_BPX_JOBNAME": "ZWE1DS1",        
"ZWED_agent_http_port": "8542",   
"_TAG_REDIR_OUT": "txt",          
"ZWED_node_https_port": "8544",   
ZWED0130I - (HTTPS) About to start listening on 0.0.0.0:8544  
ZWED0032I - Server is ready at https://0.0.0.0:8544

ZWED0033I - The http port given to the APIML is: undefined
The https port given to the APIML is: 8544   

In file instance.env, I don't see any APIML port ?

£ APIML variables                                                               
CATALOG_PORT=7552 £ the port the API catalog service will use                   
DISCOVERY_PORT=7553 £ the port the discovery service will use                   
GATEWAY_PORT=7554 £ the port the API gateway service will use                   
APIML_ENABLE_SSO=false                                                          
                                                                                
£ explorer variables                                                            
JOBS_API_PORT=8545 £ the port the jobs API service will use                     
FILES_API_PORT=8547 £ the port the files API service will use                   
JES_EXPLORER_UI_PORT=8546 £ the port the jes-explorer UI service will use       
MVS_EXPLORER_UI_PORT=8548 £ the port the mvs-explorer UI service will use       
USS_EXPLORER_UI_PORT=8550 £ the port the uss-explorer UI service will use       
                                                                                
£ Zowe Desktop/app framework variables                                          
ZOWE_ZLUX_SERVER_HTTPS_PORT=8544                                                
ZOWE_ZSS_SERVER_PORT=8542                                                       
ZOWE_ZSS_XMEM_SERVER_NAME=ZWESIS_STD                                            
ZOWE_ZLUX_SSH_PORT=22                                                           
ZOWE_ZLUX_TELNET_PORT=23

**Comment by F-LEMANER** [comment]
[zowe log.txt](https://github.com/zowe/community/files/4487246/zowe.log.txt)

ZOWE log

**Comment by F-LEMANER** [comment]
Error in TCPIP PROFILE in port reservation
 8544 TCP ZWES*                ; ZOWE ZLUX server  

should be :  8544 TCP ZWE*                ; ZOWE ZLUX server

**Comment by Joe-Winchester** [comment]
Hi @F-LEMANER - is there anything outstanding left to be done ?  It looks as though you've closed the issue yourself.

**Comment by F-LEMANER** [comment]
Hello, Nothing more to do
