### ISSUE TITLE
API catalog errors 

### ISSUE THREAD

**Issue by dprucker** [zowe/community#62]
**Describe the bug**
We are in the process of installing the Zowe framework in our test environment which is running z/OS 2.3. We have been getting some unexpected errors in the process when we start ZOWESVR. Below after STDERR is what we are receiving in the STDERR output and I am not sure if this is related to the issue we are seeing under STDOUT which can be found in the attached file. We our STDOUT log fills significantly when Zowe is running are it seems to be looping messages. The errors apart of these messages all seem to point toward the API catalog and more specifically the gateway services. I was hoping someone could lend some insight into what is occurring and if i could be an incorrect parameter in one of the config files or our certificates are not correct. 

Thank you in advance, 
Dylan 
[zowe_api_errors.txt](https://github.com/zowe/community/files/2998303/zowe_api_errors.txt)

**Logs**
**STDERR**
_tls_common.js:69
      c.context.setCert(options.cert);
                ¬

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:69:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/sys/var/zowe/1.0.0/jes_explorer/server/src/index.js:144:7)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
_tls_common.js:69
      c.context.setCert(options.cert);
                ¬

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:69:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/sys/var/zowe/1.0.0/uss_explorer/server/src/index.js:144:7)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
_tls_common.js:69
      c.context.setCert(options.cert);
                ¬

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:69:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/sys/var/zowe/1.0.0/mvs_explorer/server/src/index.js:144:7)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

**Details**
 - Version and build number: 1.0.0 
 - Test environment:  z/OS V2.3

**Web Browser Details (if the bug relates to Zowe Desktop usage):**
 - OS: [e.g. macOS, Windows]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 71.0.3578.98]

**Comment by Joe-Winchester** [comment]
@petr-galik - this looks an API problem so routing to you.  If you think it's an install problem then please let me know or likewise if you think we need a deep dive webex to diagnose.

**Comment by dprucker** [comment]
Thank you for the response Joe. We did follow through the instruction thoroughly and created certs that were causing problems on our beginning install attempts  I am wondering if it is a setting change in one of the json files, from something set by the install script. Looking at the installation log there does not seem to be any stand out problems that would be the cause, though i did just notice a JVMJ9VM015W message in there not sure if that would have any connection. Thank you again for the response, look forward to any insight.

**Comment by ilkinabdullayev** [comment]
Hi everybody,
@dprucker Thanks for reporting the issue. I'll take a look at this from api-ml side.

**Comment by Tbr00ksy** [comment]
@ilkinabdullayev has this issue been resolved? if so can we close out the issue?

**Comment by balhar-jakub** [comment]
@jalel01 Should we maybe move it to our repo and see whether it is still valid and possibly close it?

**Comment by jalel01** [comment]
@balhar-jakub yes lets do that.
